// This file was auto-generated by ML.NET Model Builder. 

using System;
using PredictiveMaintenanceML.Model;

namespace PredictiveMaintenanceML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                UDI = 1F,
                Type = @"M",
                Air_temperature = 298.1F,
                Process_temperature = 308.6F,
                Rotational_speed = 1551F,
                Torque = 42.8F,
                Tool_wear = 0F
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");
            Console.WriteLine($"UDI: {sampleData.UDI}");
            Console.WriteLine($"Type: {sampleData.Type}");
            Console.WriteLine($"Air_temperature: {sampleData.Air_temperature}");
            Console.WriteLine($"Process_temperature: {sampleData.Process_temperature}");
            Console.WriteLine($"Rotational_speed: {sampleData.Rotational_speed}");
            Console.WriteLine($"Torque: {sampleData.Torque}");
            Console.WriteLine($"Tool_wear: {sampleData.Tool_wear}");
            Console.WriteLine($"\n\nPredicted Machine_failure value {predictionResult.Prediction} \nPredicted Machine_failure scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
